### PR TITLE
Fixed lint warning with body length

### PR DESCRIPTION
**Pull request by buh**
#skip_changelog

### CODE REVIEW

**Comment by buh** [comment]
What do you mean?

**Comment by b-onc** [comment]
@buh This linter warning came from PR #271 and danger posted a comment. It should've been resolved in that PR, before merging it.
Ideally, we don't want danger to post any warnings, especially linter ones.

**Comment by buh** [comment]
What should I do now?

**Comment by b-onc** [comment]
@buh Let's merge this PR but in the future, handle linter warnings in the PRs that caused them, not in another PR

**Pull request merged**
