### PR TITLE
[CIS-2017] Make it possible to send giphy messages programmatically

### PR DESCRIPTION
**Pull request by bielikb**
### 🔗 Issue Links

CIS-2017
#2120

### 🎯 Goal

Make it possible to send giphy messages programmatically

### 📝 Summary

This change exposes initializer of `GiphyAttachmentPayload` & `LinkAttachmentPayload`. This change allows the integrator to create new giphy messages in chat.

Example:
```swift
...
let gifURL = media.url(rendition: .fixedWidth, fileType: .gif)

// StreamChat part
let attachment = GiphyAttachmentPayload(title: "Title of the giphy", previewURL: gifURL)
let attachments = [AnyAttachmentPayload(payload: attachment)]
channelController?.createNewMessage(
    text: "",
    attachments: attachments)
)
```

### 🎨 Showcase

Simulator Screen Shot - iPhone 12 Pro - 2022-06-27 at 14 36 08

### 🧪 Manual Testing Notes

_Explain how this change can be tested manually, if applicable._

### ☑️ Contributor Checklist
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] Changelog is updated with client-facing changes
- [x] New code is covered by unit tests
- [x] This change follows zero ⚠️ policy (required)
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (docusaurus, tutorial, CMS)

### 🎁 Meme

_Provide a funny gif or image that relates to your work on this pull request. (Optional)_

### CODE REVIEW

**Review by b-onc — COMMENTED** [review]
I don't think it's correct to call _all_ gifs as `GiphyAttachment`s. How much work would it be to expose a new attachment type for gifs, just that it doesn't have the giphy badge on it? This will allow all gif urls to be rendered as Giphys, which is not bad but also not correct

**Review by nuno-vieira — APPROVED** [review]
LGTM! ✅

**Comment by nuno-vieira** [comment]
> I don't think it's correct to call _all_ gifs as `GiphyAttachment`s. How much work would it be to expose a new attachment type for gifs, just that it doesn't have the giphy badge on it? This will allow all gif urls to be rendered as Giphys, which is not bad but also not correct

The idea here is to be able to send Giphies programmatically. Not "gifs" in general. I don't think we are calling all gifs Giphy attachments in this case. In the ticket of the customer, he wants to send giphies, not generic gifs.

**Comment by bielikb** [comment]
> > The idea here is to be able to send Giphies programmatically. Not "gifs" in general. I don't think we are calling all gifs Giphy attachments in this case. In the ticket of the customer, he wants to send giphies, not generic gifs.
> 
> Is there anything that stops users to use it to send any gif URL? Or even "any" attachment?

We've support sending different types of attachment payloads:
When it comes down to `gifs` in general, integrator can either leverage `ImageAttachment` which will be processed as a static image (same behaviour with SwiftUI)
This PR brings possibility to leverage also `GiphyAttachmentPayload` that comes with the support to display animated gifs + additional `giphy badge` overlay.

Screenshot 2022-06-27 at 16 27 26

@b-onc comment is on point, but outside of the scope of this PR.

**Review by adolfogarza — APPROVED** [review]

**Pull request merged**
