### PR TITLE
Channel's config: Accept value null in commands

### PR DESCRIPTION
**Pull request by mpodeszwa**
# Submit a pull request

## CLA

- [X] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [X] The code changes follow best practices
- [ ] Code changes are tested (add some information if not applicable)

## Description of the pull request

When commands are disabled, API is returning null instead of empty array and parsing fails.

### CODE REVIEW

**Comment by janweinkauff** [comment]
Same issue for us if we disable commands over the Dashboard for the chat type. Also if you just clear the text field for commands.

I was also preparing a pull request to fix this issue. Thx @mpodeszwa 👌🏻

**Comment by buh** [comment]
I fixed it, will be in the next release. I'll let you know guys.

**Comment by buh** [comment]
I don't want `commands` make optional, it always would be as an array.

**Comment by buh** [comment]
Fixed in v.1.2.11

**Pull request closed without merging**
