### PR TITLE
Add parseMentionedUsers parameter to Client.send(message: ...)

### LINKED ISSUE #338: Option for applying mention users
## What are you trying to achieve?
I want to customize mention users by myself but SDK override it.

## If possible, how can you achieve this currently?
Currently, I need to modify SDK source code as a work around. There should be a better way.

## What would be the better way?
This is current method inside Client+Channel.swift. 
`func send(message: Message, to channel: Channel, _ completion: @escaping Client.Completion<MessageResponse>) -> Cancellable
`

It would be better to give developers an option for overriding mention users like the following.
`func send(message: Message, to channel: Channel, overrideMentionUsers: Boolean = true,  _ completion: @escaping Client.Completion<MessageResponse>) -> Cancellable
`

Add an extra parameter which will allow developers to choose. And only override mention users if it is true.

## GetStream Environment
**GetStream Chat version:** - 2.2.5
**GetStream Chat frameworks:** StreamChatClient
**iOS version:** 13
**Swift version:** 5.2
**Xcode version:** 11
**Device:**

### PR DESCRIPTION
**Pull request by cardoso**
I opted to add parseMentionedUsers parameter with default true to avoid a breaking change

Closes #338

### CODE REVIEW

**Comment by cardoso** [comment]
@b-onc can you be more specific? Won't moving this logic to Presenter cause a breaking change?

**Comment by b-onc** [comment]
@cardoso You're right! So I propose this:
- Keep the changes you've done (parseMentionedUsers param for Client.send). This resolves the issue for users using LLC
- Add a similar logic to the presenter. If a user is using UI SDK, they won't be directly using Client.send, so they should have access to this API too.

**Comment by b-onc** [comment]
One more last API is needed: `ChatViewController.parseMentionedUsersOnSend` property, so people using our VCs can do:
```swift
func viewDidLoad() {
  ...
  self.parseMentionedUsersOnSend = false // so they can apply their custom logic
  ...
}
```
And ChatViewController will pass this to ChannelPresenter.send on `ChatViewController+Composer.swift:L196`
I don't think this needs to be in the `init`, a property defaulting to `true` is fine.
This would finalize the PR! Please make sure to add this addition to CHANGELOG.

**Comment by cardoso** [comment]
@b-onc done 👍

**Pull request merged**
