### PR TITLE
[CIS-1911] Return Sonar Analysis on push

### PR DESCRIPTION
**Pull request by alteral**
### 🔗 Issue Links

- https://stream-io.atlassian.net/browse/CIS-1911
- https://github.com/GetStream/stream-chat-swift/pull/2033

### 🎯 Goal

- To run Sonar Analysis on `push` to `main` and `develop`

### 📝 Summary

- Return Sonar Analysis on push
- Remove slack actions that had a condition to fire on `push`

### ☑️ Contributor Checklist
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [x] This change follows zero ⚠️ policy (required)
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (docusaurus, tutorial, CMS)

### CODE REVIEW

**Review by nuno-vieira — APPROVED** [review]
LGTM! ✅

**Comment by nuno-vieira** [comment]
> SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=GetStream_stream-chat-swift&pullRequest=2049)
> 
> [Bug](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-swift&pullRequest=2049&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-swift&pullRequest=2049&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-swift&pullRequest=2049&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-swift&pullRequest=2049&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-swift&pullRequest=2049&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-swift&pullRequest=2049&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=GetStream_stream-chat-swift&pullRequest=2049&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=GetStream_stream-chat-swift&pullRequest=2049&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=GetStream_stream-chat-swift&pullRequest=2049&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-swift&pullRequest=2049&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-swift&pullRequest=2049&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-swift&pullRequest=2049&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-swift&pullRequest=2049&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-swift&pullRequest=2049&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-swift&pullRequest=2049&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-swift&pullRequest=2049&metric=new_duplicated_lines_density&view=list)

@alteral The SonarCloud is still failing based on the previous PRs 🤔

**Comment by alteral** [comment]
@nuno-vieira, as far as I understand it fails until we won't run Sonar Analysis on `develop`. I triggered it locally, let's see.

**Review by nuno-vieira — APPROVED** [review]
LGTM! ✅

**Pull request merged**
