### PR TITLE
Add user privacy settings to control user events

### PR DESCRIPTION
**Pull request by nuno-vieira**
### 🔗 Issue Links
Resolves https://github.com/GetStream/ios-issues-tracking/issues/774

### 🎯 Goal
Allow the user to control whether he wants to share, read, or type events.

### 📝 Summary
- Adds `UserPrivacySettings` to `ChatClient.connectUser()`
- Adds `UserPrivacySettings` to `CurrentUserController.updateUserData()`
- Adds `ChatCurrentUser.privacySettings`
- Only send typing events if `ChatCurrentUser.privacySettings.typingIndicator.enabled`
- Allow to edit user privacy settings in the Demo App Configuration.
- Allow to edit user privacy settings in the Demo App Profile View.

### 🧪 Manual Testing Notes
- Open Demo App Configuration
- Enable/Disable typing indicators and read indicators
- When connecting the user, the connectUser call in proxyman should include the privacy settings
- If typing events are disabled, when sending a message, it should not send typing events (Check with another device and user)
- if read receipts are disabled, when reading a message, it should not appear in the delivery receipts of the other user
- Do the same when updating the user profile (Open the user profile view and update the privacy settings)

### ☑️ Contributor Checklist
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] This change follows zero ⚠️ policy (required)
- [x] This change should be manually QAed
- [x] Changelog is updated with client-facing changes
- [x] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (docusaurus, tutorial, CMS)

### CODE REVIEW

**Review by martinmitrevski — COMMENTED** [review]
@nuno-vieira don't we also need UI components updates? E.g. don't send typing events, don't show read indicators.

**Comment by nuno-vieira** [comment]
> @nuno-vieira don't we also need UI components updates? E.g. don't send typing events, don't show read indicators.

Discussed internally. Answer: No 👍

**Review by myandrienko — COMMENTED** [review]
General comment: let's rename "private settings" to "**privacy** settings" everywhere, to be consistent with backend and the spec?

**Comment by nuno-vieira** [comment]
> General comment: let's rename "private settings" to "**privacy** settings" everywhere, to be consistent with backend and the spec?

Yes this was actually a typo on my end. I read "private" instead of "privacy" in the backend specs. Thanks for the catch 👍

**Review by martinmitrevski — APPROVED** [review]
Great work 👌  We only need to add some docs around this, maybe a sentence or two in the LLC ones, around the `updateUserData`? (that's not blocking this PR, since it's not part of docusaurus).

**Comment by testableapple** [comment]
[QA] Two notes:
- Turning off the read receipts seems to be not working
- Updating the user profile does not have any effect (the data is reset on closing the view)

**Comment by testableapple** [comment]
Seems like enabling/disabling read indicators does not work as expected:
- ✅ Works as expected for Leia and Han
- ⚠️ Does not work for Luke and Chewbacca

**Review by testableapple — APPROVED** [review]

**Pull request merged**
