### PR TITLE
Changing assets to preserve vector data

### PR DESCRIPTION
**Pull request by adamrushy**
This PR will change all assets to preserve vector data. This will decrease the overall bundle size for the SDK.

### CODE REVIEW

**Review by nuno-vieira — APPROVED** [review]
LGTM ✅

**Comment by adamrushy** [comment]
Snapshot tests are failing, but also failing in `main` on Xcode 13. We need to validate on Xcode 12 and raise a task to investigate further.

**Comment by tbarbugli** [comment]
@adamrushy ui tests are failing, can you check how snapshots differ

**Comment by adamrushy** [comment]
@tbarbugli working on it

**Comment by adamrushy** [comment]
It looks like we're dynamically drawing imageViews within the app which means preserve vector data will effectively blur the images. I am going to close this PR so we can investigate further.

**Pull request closed without merging**
