### PR TITLE
Show human-readable error's description when request fails...

### LINKED ISSUE #104: Network connectivity error is not human-readable
## What did you do?

Some request failed because of poor internet connection.

## What did you expect to happen?

I expect error to be human readable

## What happened instead?

User sees this error:
Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-26 at 11 53 32

### PR DESCRIPTION
**Pull request by mpodeszwa**
… because of connectivity issue

# Submit a pull request

## CLA

- [X] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [X] The code changes follow best practices
- [ ] Code changes are tested - this area was not tested before so I didn't add tests :(

## Description of the pull request
Fixes #104 
Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-26 at 11 56 31

### CODE REVIEW

**Comment by mpodeszwa** [comment]
check failed with error:
```
Could not set up API to Code Review site for Danger

For your GitHub repo, you need to expose: DANGER_GITHUB_API_TOKEN
```
🤔

**Comment by b-onc** [comment]
Hello @mpodeszwa ,

Thanks a lot for the PR! Much appreciated 🙌

Don't worry about the danger error, I don't know why it failed - we've correctly setup the parameters and it was working before, I'll check it...

Regarding the PR: Instead of changing the error message, I believe it'd be more beneficial to change how the errors are displayed. Instead of using `show(error:)` we can make use of `show(errorMessage:)` and provide the message there.

So for example, in `ChatViewController.swift:L370`:
```swift
        case .error(let error):
            show(error: error)
        }
```
we can do:
```swift
        case .error(let error):
            show(errorMessage: error.localizedDescription)
        }
```
or similar. Then we wouldn't have the fragmentation (some error cases have description with full error, some have `localizedDescription`)
_Or_,
In `Banners.show(error:)`, you can change:
```swift
var message = "\(error)"
```
to
```swift
var message = "\(error.localizedDescription)"
```

Personally I'd prefer the 2nd approach.

**Comment by mpodeszwa** [comment]
Maybe danger failed, because it's a PR from my fork? :)

I'm not sure if your suggestions will work, because `localizedDescription` uses  `errorDescription` underneath, so I think `errorDescription` in `ClientError` has to use `localizedDescription` of a nested error.

Btw, in my project I override `open func show(errorMessage: String)` and `open func show(error: Error)` of `ViewController` and I need to somehow get nice error message to show in my app. :) Fixing this just in `Banner` doesn't solve my issue.

**Comment by b-onc** [comment]
@mpodeszwa I see the problem more clearly now. In that case, can you make sure in `ClientError.errorDescription` wherever the string interpolation of the error is used, it's changed to `localizedDescription`? You did it for `responseError` and `requestFailed`, but for unity others should follow suit, too.

**Comment by mpodeszwa** [comment]
Absolutely, I missed that 🙈

**Comment by mpodeszwa** [comment]
Modified all errors in `ClientError`.

I just found an issue with readability of an encoding error. Unfortunately, I didn't have any idea how I can fix it easily. 

It's not a priority for me, because it shouldn't happen very often. Maybe you could put it to your backlog with a low priority? 😁 

To easily reproduce, just modify `encode` of `Attachment` like this:
```
    public func encode(to encoder: Encoder) throws {
//        guard self != .unknown else {
            throw ClientError.encodingFailure(EncodingError.valueUnsupported, object: self)
//        }
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
```
and send an attachment.


Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-26 at 18 08 50

**Comment by mpodeszwa** [comment]
Hi @b-onc , can you please take a look at #106 , it should be slightly better than this PR 😄

**Comment by b-onc** [comment]
@mpodeszwa I'm closing this since you've opened a better PR for the same issue

**Pull request closed without merging**
