### PR TITLE
Fix `ChatMessageListVC` swipe-to-reply pan gesture recognizer overriding native swipe go-back gesture

### PR DESCRIPTION
**Pull request by pm-dev**
### 🔗 Issue Links

N/A

### 🎯 Goal

Similar to https://github.com/GetStream/stream-chat-swift/pull/3000, the `ChatMessageListVC` is disabling the native swipe to go back functionality.

### 📝 Summary

The `ChatMessageListVC` uses a pan gesture recognizer for its swipe-to-reply functionality, but this pan gesture recognizer disables the navigation controller's interactive pop functionality.

### 🛠 Implementation

This PR prevents the pan gesture recognizer from being added to its view if `components.messageSwipeToReplyEnabled` is turned off. An alternative implementation would have made the pan gesture recognizer a stored property on the VC and still added it to the view, so that clients could control it's `enabled` property.

We've implemented a workaround for the time being, which is to subclass ChatMessageListVC and implement `UIGestureRecognizerDelegate`'s `shouldRequireFailureOf` function, so that the pan gesture recognizer waits for the native interactive pop gesture to fail.

### ☑️ Contributor Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] This change follows zero ⚠️ policy (required)
- [x] This change should be manually QAed
- [x] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (docusaurus, tutorial, CMS)

### CODE REVIEW

**Comment by nuno-vieira** [comment]
Hi @pm-dev, is this maybe an issue on your app only? At least with our Demo App, I can easily swipe back, with both the swipe to reply enabled and disabled 🤔

**Comment by pm-dev** [comment]
@nuno-vieira 
The native swipe-to-go-back functionality works out of the box in the demo app because it uses the default `backBarButtonItem`. However if anyone wants a custom back button icon, they'll need to set `leftBarButtonItem = UIBarButtonItem(...)`. When a vc has its `navigationItem.leftBarButtonItem` set, this disables the interactive pop gesture for that view controller, and the only way to re-enable it, is to implement the navigation controller's interactive pop gesture recognizer's delegate yourself.

Most production apps will not use Apple's back icon, meaning it's likely they're already explicitly setting `interactivePopGestureRecognizer.delegate` and implementing `gestureRecognizerShouldBegin`. However to make this work with `ChatChannelVC` they'll also need to implement `gestureRecognizer(_:shouldBeRequiredToFailBy:)` and return true. We've done this, and now everything works as expected.

Perhaps this is the correct fix, but I would argue it's also unnecessary and asking for problems to add an enabled gesture recognizer to a view when it's not being used. At the very least I would expect it's enabled/disabled to be based on `components.messageSwipeToReplyEnabled`

To see the swipe-to-go-back behavior of native vs custom back buttons:
[Tester.zip](https://github.com/GetStream/stream-chat-swift/files/14199653/Tester.zip)

**Comment by nuno-vieira** [comment]
> @nuno-vieira The native swipe-to-go-back functionality works out of the box in the demo app because it uses the default `backBarButtonItem`. However if anyone wants a custom back button icon, they'll need to set `leftBarButtonItem = UIBarButtonItem(...)`. When a vc has its `navigationItem.leftBarButtonItem` set, this disables the interactive pop gesture for that view controller, and the only way to re-enable it, is to implement the navigation controller's interactive pop gesture recognizer's delegate yourself.
> 
> Most production apps will not use Apple's back icon, meaning it's likely they're already explicitly setting `interactivePopGestureRecognizer.delegate` and implementing `gestureRecognizerShouldBegin`. However to make this work with `ChatChannelVC` they'll also need to implement `gestureRecognizer(_:shouldBeRequiredToFailBy:)` and return true. We've done this, and now everything works as expected.
> 
> Perhaps this is the correct fix, but I would argue it's also unnecessary and asking for problems to add an enabled gesture recognizer to a view when it's not being used. At the very least I would expect it's enabled/disabled to be based on `components.messageSwipeToReplyEnabled`
> 
> To see the swipe-to-go-back behavior of native vs custom back buttons: [Tester.zip](https://github.com/GetStream/stream-chat-swift/files/14199653/Tester.zip)

Thanks for the explanation 👍 We will improve this and take it from here as well. Thank you once again 🙏

**Comment by nuno-vieira** [comment]
Closing this one in favor of this: https://github.com/GetStream/stream-chat-swift/pull/3029

**Pull request closed without merging**
