### PR TITLE
Remove forgotten `Reachability` import

### PR DESCRIPTION
**Pull request by VojtaStavik**
- Builds were failing because of a forgotten `import Reachability`
- I have to make parts of the `Reachability` class public so we can access them from the `Core` framework.

### CODE REVIEW

**Comment by b-onc** [comment]
Would it make sense to include CI fixes in this PR too, since they're related?

**Comment by buh** [comment]
Our Example app has dependencies on `Reachability` and `Gzip`. Can you clean up it too?

**Comment by VojtaStavik** [comment]
@b-onc I'll do it in a separate PR if you don't mind.

**Comment by VojtaStavik** [comment]
@buh Also, coming in a follow-up PR

**Pull request merged**
