### PR TITLE
[CIS-1324] Fastlane lane to create xcframeworks

### PR DESCRIPTION
**Pull request by polqf**
### 🔗 Issue Link
https://stream-io.atlassian.net/browse/CIS-1324

### 🎯 Goal

To have a fastlane lane that would create all the needed packages to distribute StreamChat/StreamChatUI

### 🛠 Implementation

On top of that, there's also a bash script to remove duplicated symbols that are created when frameworks are nested.

### ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Affected documentation updated (docusaurus, tutorial, CMS (task created)

### CODE REVIEW

**Comment by jeroenleenarts** [comment]
One question. The removal of unneeded symbols. Is that specifically to prevent warnings about this from AppStore Connect. It is the biggest addition of original code. So maybe add a comment on why this is needed.

**Review by jeroenleenarts — APPROVED** [review]
Good idea to use the Fastlane plugin for this.

**Review by adamrushy — APPROVED** [review]
Looks good to me 🔥

**Comment by evsaev** [comment]
> One question. The removal of unneeded symbols. Is that specifically to prevent warnings about this from AppStore Connect. It is the biggest addition of original code. So maybe add a comment on why this is needed.

Yep, that would be awesome 👍 Got stuck understanding the issue that we're fixing there.

**Review by bielikb — APPROVED** [review]

**Comment by polqf** [comment]
@evsaev @jeroenleenarts @adamrushy comment added to explain what remove_unneeded_symbols is doing: https://github.com/GetStream/stream-chat-swift/pull/1619/commits/d225fb8b7fe5a1e10d1ae61964c4615f74794591

**Pull request merged**
